image: golang:latest

variables:
  REPO_NAME: myproject

before_script:
  - mkdir -p /usr/lib/go-1.6/src/$REPO_NAME
  - cd /usr/lib/go-1.6/src/$REPO_NAME

stages:
    - test
    - build
    - deploy

format:
    stage: test
    tags:
      - test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
#       - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    tags:
      - test
    script:
      - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/binary
    artifacts:
      paths:
        - binary


run:
    stage: deploy
    tags:
      - test
    script:
      - $CI_PROJECT_DIR/binary

