image: golang:latest

variables:
  REPO_NAME: Simple-Golang-HTTP-Server

before_script:
  - ln -svf $CI_PROJECT_DIR /usr/lib/go-1.6/src
  - cd /usr/lib/go-1.6/src/$REPO_NAME

stages:
    - test
    - build
    - deploy

format:
    stage: test
    tags:
      - test
    script:
      - go fmt
      - go vet
#       - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    tags:
      - test
    script:
      - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/gohttp
    artifacts:
      paths:
        - gohttp

testenv:
    stage: deploy
    tags:
      - test
    script:
      - sudo service gohttp stop
      - cp -f /usr/lib/go-1.6/src/$REPO_NAME/gohttp /usr/local/bin/
      - sudo service gohttp start
    only:
      - master

prodenv:
    stage: deploy
    tags:
      - prod
    script:
      - sudo service gohttp stop
      - cp -f /usr/lib/go-1.6/src/$REPO_NAME/gohttp /usr/local/bin/
      - sudo service gohttp start
    only:
      - production
    dependencies:
      - compile