image: golang:latest

variables:
  REPO_NAME: Simple-Golang-HTTP-Server

before_script:
  - echo $CI_PROJECT_DIR
  - ln -svf $CI_PROJECT_DIR /usr/lib/go-1.6/src
# '/usr/local/src/gohttp/Simple-Golang-HTTP-Server' -> '/home/gitlab-runner/builds/4e9c8eeb/0/root/Simple-Golang-HTTP-Server'
  - echo $REPO_NAME
  - cd /usr/local/src/$REPO_NAME

stages:
    - test
    - build
    - deploy

format:
    stage: test
    tags:
      - test
    script:
      - go fmt
      - go vet
#       - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    tags:
      - test
    script:
      - go build -race -ldflags "-extldflags '-static'" -o bin/gohttp
    artifacts:
      paths:
        - gohttp


run:
    stage: deploy
    tags:
      - test
    script:
      - echo $CI_PROJECT_DIR
      - cd /usr/local/src/$REPO_NAME/
      - bin/gohttp
